-- Migration: 001_initial_schema.sql
-- Description: Initial database schema for Bitversity platform
-- Created: 2024-01-01
-- Version: 1.0.0

-- This file contains the initial database schema
-- It should match the main schema.sql file

-- Migration will be applied by the migration system
-- Do not edit this file after it has been deployed

SELECT '001_initial_schema.sql migration file - use main schema.sql for setup' as message;